pretrained_model_path: "CompVis/stable-diffusion-v1-4"
output_dir: "./workdir/man-skiing/"
######## TEXTUAL INVERSION ########
placeholder_tokens: "<s1>|<s2>"
initializer_tokens: "man|skiing"
sentence_component: "<o>|<v>"
###################################
num_s1_train_epochs: 250
exp_use_attention_localization: True
exp_localization_weight: 5e-4

train_data:
  video_path: "./data/man-skiing/"
  prompt: "a <s1> man is <s2>"
  n_sample_frames: 16
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  video_length: 16
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 500
trainable_modules:
  - "attn2.to_k"
  - "attn2.to_v"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True